config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'web/videos#index'

  scope module: :web do
    get 'search', to: 'videos#search'
    resources :videos, only: [:show] do
        resources :comments, only:[:new, :create]
        resources :likes, only:[:create, :destroy]
    end
    resources :series, only: [:show]
    resources :creators, only: [:show]
    resources :users, only: [:show] do
      member do
        get 'comments'
        get 'likes'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :video

  validates :content, presence: true
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :series

  # :through パラメータについて
  # has_many と has_one は :throughパラメータを使って、中間テーブルを経由したアソシエーションを定義できる。
  # 
  # [備考]
  # ・ https://railsguides.jp/association_basics.html#has-many-through%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91
  # ・ https://babiy3104.hateblo.jp/entry/2014/02/22/152341
  has_many :videos, through: :series

  # Scope について
  # Seriesモデル (models/series.rb) 内の記述を参照すること。
  scope :has_visible_videos, -> { where(creator_id: Series.has_visible_videos.group(:creator_id).pluck(:creator_id)) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :video
  validates :user_id, presence: true
  validates :video_id, presence: true
end

app/models/series.rb
class Series < ApplicationRecord
  has_many :videos
  belongs_to :creator

  # has_many の第二引数について
  # has_many は第二引数にProcを渡すことができ、アソシエーション実行時の条件(where)や順序(order by)などを指定できる
  #
  # [備考]
  # ・ https://qiita.com/okamos/items/724a4a162dfa9e27754a
  # ・ http://ducktypelabs.com/using-scope-with-associations/
  has_many :visible_videos,
           -> { visible },
           class_name:  'Video'

  # Scope について
  # クエリアセットのようなもの。よく実行するクエリを関数化して置くようなイメージ
  #
  # [備考]
  # ・https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97
  # ・https://programming-beginner-zeroichi.jp/articles/62
  scope :has_visible_videos, -> { joins(:visible_videos).group('series_id') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorite_videos, through: :likes, source: :video

  def favorite(video)
    likes.create(video_id: video.id)
  end

  def unfavorite(video)
    likes.find_by(video_id: video.id).destroy
  end

   def favorite?(video)
    favorite_videos.include?(video)
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :series
  has_many :comments
  has_many :likes, dependent: :destroy

  # Delegate（移譲）
  # belongs_toは :through が使えないので、Associationでcreatorアクセスはできない。
  # なので、代わりにDelegationを使っている。
  # 
  # [備考]
  # ・ https://blog.toshimaru.net/belongs_to-through/
  # ・ http://www.ckazu.info/blog/2013/12/14/delegate_allow_nil/
  delegate :creator, to: :series
  # Railsにおける Enum について
  # Integerや、Booleanのカラムに対して、列挙型ぽく便利メソッドなどが使えるようになる。
  # 
  # [備考]
  # ・ http://ruby-rails.hatenadiary.com/entry/20150710/1436461745
  enum status_code: { visible: 1, invisible: 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def layout
    render layout: 'web/layouts/base'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/web/base_controller.rb
class ParametersError < StandardError; end

module Web
  class BaseController < ApplicationController

    # rescue_from について
    # 所定のアクションが実行されている間に raise されたエラーは最終的にここで、catchされて処理される。
    #
    # [備考]
    # ・ https://techracho.bpsinc.jp/hachi8833/2018_04_09/54676
    rescue_from Exception,       with: :handle_500
    rescue_from ParametersError, with: :handle_404

    def handle_404(e = nil)
      @error = e
      render 'web/errors/404', layout: 'web/layouts/base', status: :not_found
    end

    def handle_500(e = nil)
      @error = e
      render 'web/errors/500', layout: 'web/layouts/base', status: :internal_server_error
    end

    def error_obj(code = SYSTEM_ERROR, msg = nil, flg: 1)
      {
        error: {
          error_flg: flg,
          error_code: code,
          error_message: msg
        }
      }
    end
  end
end

app/controllers/web/comments_controller.rb
module Web
  class CommentsController < Web::BaseController
    before_action :find_video, only: [:new, :create]

    def new
      @comment = Comment.new
      render layout: 'web/layouts/base'
    end

    def create
      Comment.create(comment_params)
      redirect_to  @video
    end

    def find_video
       @video = Video.find(params[:video_id])
    end

    private
    def comment_params
      params.require(:comment).permit(:content).merge(user_id: current_user.id, video_id: params[:video_id])
    end

  end
end

app/controllers/web/likes_controller.rb
module Web
  class LikesController < Web::BaseController
    before_action :authenticate_user!, only: [:create, :destroy]

    def create
      video = Video.find(params[:video_id])
      current_user.favorite(video)
      @videos = Video.all
    end

    def destroy
      video = Video.find(params[:id])
      current_user.unfavorite(video)
      @videos = Video.all
    end
  end
end

app/controllers/web/users_controller.rb
module Web
  class UsersController < Web::BaseController
    before_action :set_user

    def show
      @comments = @user.comments
      @likes = current_user.likes
      render layout: 'web/layouts/base'
    end

    def comments
      @comments = @user.comments
      render layout: 'web/layouts/base'
    end

    def likes
      @likes = @user.likes
      render layout: 'web/layouts/base'
    end

    private
    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/web/videos_controller.rb
module Web
  class VideosController < Web::BaseController
    def index
      @q = Video.ransack(params[:q])
      @videos = @q.result(distinct: true).order(created_at: "DESC")
      render layout: 'web/layouts/base'
    end

    def search
      @q = Video.search(search_params)
      @videos = @q.result(distinct: true).order(created_at: "DESC")
      render layout: 'web/layouts/base'
    end

    def show
      @video = Video.find_by(video_id: video_id)

      # エラーハンドリングに関して
      # ここで raise された、エラーは Web::BaseController に書いてある rescue_from によって catchされて、500・404ページにリダイレクトされるようになっている。
      unless @video
        raise ParametersError, "Cannot find the video with id: #{video_id}"
      end

      unless @video.visible?
        raise ParametersError, "The video(id: #{video_id}) is invisible."
      end

      # layout: パラメータでレイアウトファイルを指定できる。
      render layout: 'web/layouts/base'
    end


    def video_id
      params.require(:id)
    end

    private

    def search_params
      params.require(:q).permit(:title_cont)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web/comments/new.html.erb
<div id="section-contents-inner-video">
  <div class="section-contents-inner-video-inner">
  <%= render partial: 'web/videos/partials/video_player', locals: {
    video_url: @video.file_url,
    thumb_url: @video.thumb_url
  }%>
  <div class="section-contents-inner-video-inner-detail">
    <div class="section-contents-inner-video-inner-detail-wrap clearfix">
      <div class="section-contents-inner-video-inner-detail-title">
        <p>
        <%= @video.title %>
        </p>
      </div>
    </div>
    <div class="section-contents-inner-video-inner-detail-serise clearfix">
      <div class="section-contents-inner-video-inner-detail-serise-inner">
        <div class="section-contents-inner-video-inner-detail-serise-l">
          <div class="section-contents-inner-video-inner-detail-serise-image" style="background-image:url(<%= @video.creator.icon_url %>);"></div>
        </div>
        <div class="section-contents-inner-video-inner-detail-serise-r">
          <div class="section-contents-inner-video-inner-detail-serise-text">
            <p><%= @video.creator.name %></p>
          </div>
        </div>
      </div>
    </div>
      <%= form_for [@video, @comment] do |f| %>
         <!-- <div style="margin: 8px 0">
            <%#= f.label :評価, style: {'margin-right' => 8} %>
            <%#= f.number_field :rate, placeholder: '評価', value: '1', max: '10', min: '1', html: {class: "search__query", style: 'text-align: right;' } %>
         </div> -->
         <div style="margin: 8px 0">
            <%= f.text_area :content, placeholder: '感想', style: 'width: 100%;height: 300px;' %>
         </div>
         <div class="row">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn-default" do %>投稿する<i class="icon-arrow-right"></i>
              <% end %>
           </div>
         </div>
      <% end %>
  </div>
</div>

app/views/web/layouts/base.html.erb
<!DOCTYPE html>
<html lang="ja" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# mixi: http://mixi-platform.com/ns# website: http://ogp.me/ns/website#" class="no-js">

<%= render partial: 'web/partials/head_tags' %>

<body class="page-video">
  <%= render partial: 'web/partials/header' %>
  <main id="section-contents">
    <div class="section-contents-inner">
      <%= yield %>
    </div>
  </main>
  <%= render partial: 'web/partials/footer' %>
</body>

<%= javascript_include_tag 'web/application', 'data-turbolinks-track': 'reload' %>

</html>

app/views/web/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'web/videos/partials/like', locals: { videos: @videos, likes: @likes, like: @like}) %>")

app/views/web/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'web/videos/partials/like', locals: { videos: @videos, likes: @likes }) %>");

app/views/web/partials/_footer.html.erb
<footer id="section-footer">
  <div class="section-footer-outer">
    <div class="section-footer-outer-follow">
      <div class="section-footer-outer-follow-text">
        <p>30の公式アカウントもフォローしてね♪</p>
      </div>
      <div class="section-footer-outer-follow-btn">
        <div class="section-footer-outer-follow-btn-sns">
          <ul class="clearfix">
            <li class="twitter"><a href="https://twitter.com/vem_30" target="_blank">Twitter</a></li>
            <li class="facebook"><a href="https://www.facebook.com/vem30.jp/" target="_blank">Facebook</a></li>
            <li class="instagram"><a href="https://www.instagram.com/30_thirty_/" target="_blank">Instagram</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="section-footer-inner">
    <div class="section-footer-inner-link">
      <ul class="clearfix">
        <li><a href="http://firebug.jp/" target="_blank">運営会社</a></li>
        <li><a href="https://vem30.com/terms/">利用規約</a></li>
        <li><a href="https://vem30.com/privacy/">プライバシーポリシー</a></li>
        <li><a href="https://vem30.com/license/">ライセンス</a></li>
      </ul>
      <span>&copy;FIREBUG Inc,</span>
    </div>
  </div>
</footer><!-- /#section-footer -->

app/views/web/partials/_head_tags.html.erb
<head>
<meta charset="UTF-8">
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<%= csrf_meta_tags %>
<title>30 研修プログラム</title>


<meta name="robots" content="index,follow">

<!-- Viewportの設定 -->
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimal-ui">
<meta name="format-detection" content="telephone=no,address=no,email=no">

<!-- iOS Safari & Chrome Android Full screen -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">

<!-- アイコン指定(iOS/Android込) -->
<link rel="image_src" href="<?php echo IMG_FILE_PATH; ?>ogp_image.png">
<link rel="apple-touch-icon-precomposed" href="<?php echo IMG_FILE_PATH; ?>favicon.png">
<link rel="shortcut icon" href="<?php echo IMG_FILE_PATH; ?>favicon.ico" type="image/x-icon">
<link rel="icon" href="<?php echo IMG_FILE_PATH; ?>favicon.ico" type="image/x-icon">

<!-- スタイルシート指定 -->
<%= stylesheet_link_tag    'web/application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/web/partials/_header.html.erb
<header id="section-header">
  <div class="section-header-inner">
    <div class="section-header-inner-head clearfix">
      <ul class="menu">
        <% if user_signed_in? %>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'マイページ', user_path(current_user) %></li>
        <% else %>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>
      </ul>
      <div class="section-header-inner-head-logo">
         <h1><%= link_to '30', root_path %></a></h1>
      </div>
      </div>
  </div>
</header><!-- /#section-header -->

app/views/web/users/comments.html.erb
<div class="user_page">
  <header class="user_page-header">
    <div class="user-name">
      <h2><%= @user.nickname %></h2>
    <div class="navbar">
      <ul>
        <li><%= link_to 'コメントした動画', user_path(@user) %></li>
        <li><%= link_to 'いいねした動画', likes_user_path(@user) %></li>
      </ul>
    </div>
    </div>
  </header>
    <div id="section-contents-inner-video">
      <div class="section-contents-inner-video-inner">
          <ul class="user_page-contents">
          <% @comments.each do |comment| %>
            <li>
            <%= render partial: 'web/videos/partials/video_player', locals: {
                  video_url: comment.video.file_url,
                  thumb_url: comment.video.thumb_url
                }%>
              <div class="meta">
                  <div class="meta-title">
                    <%= comment.video.title %>
                    <%= render partial: 'web/videos/partials/like', locals: {video: comment.video} %>
                  </div>
                <div class="user_review"><%= comment.content %></div>
              </div>
            </li>
            <% end %>
           </ul>
      </div>
    </div>
</div>

app/views/web/users/likes.html.erb
<div class="user_page">
  <header class="user_page-header">
    <div class="user-name">
      <h2><%= @user.nickname %></h2>
    <div class="navbar">
      <ul>
        <li><%= link_to 'コメントした動画', comments_user_path(@user) %></li>
        <li><%= link_to 'いいねした動画', likes_user_path(@user) %></li>
      </ul>
    </div>
    </div>
  </header>
    <div id="section-contents-inner-video">
      <div class="section-contents-inner-video-inner">
          <ul class="user_page-contents">
          <% @likes.each do |like| %>
            <li>
            <%= render partial: 'web/videos/partials/video_player', locals: {
                  video_url: like.video.file_url,
                  thumb_url: like.video.thumb_url
                }%>
              <div class="meta">
                  <div class="meta-title">
                    <%= like.video.title %>
                    <%= render partial: 'web/videos/partials/like', locals: {video: like.video} %>
                  </div>
              </div>
            </li>
            <% end %>
           </ul>
      </div>
    </div>
</div>

app/views/web/users/show.html.erb
<div class="user_page">
  <header class="user_page-header">
    <div class="user-name">
      <a href="">
          <h2><%= @user.nickname %></h2>
      </a>
    </div>
  </header>
    <div id="section-contents-inner-video">
      <div class="section-contents-inner-video-inner">
          <ul class="user_page-contents">
          <% @comments.each do |comment| %>
            <li>
            <%= render partial: 'web/videos/partials/video_player', locals: {
                  video_url: comment.video.file_url,
                  thumb_url: comment.video.thumb_url
                }%>
                <%= render partial: 'web/videos/partials/like', locals: {video: comment.video} %>
              <div class="meta">
                  <div class="meta-title"><%= comment.video.title %></div>
                <div class="user_review"><%= comment.content %></div>
              </div>
            </li>
            <% end %>
           </ul>
      </div>
    </div>
</div>

app/views/web/videos/index.html.erb
<div id="section-contents-inner-video">
  <%= render partial: 'web/videos/partials/index', locals: { videos: @videos } %>
</div><!-- /#section-contents-inner-video -->

app/views/web/videos/partials/_contents_section.html.erb
<div class="section-contents-inner-video-inner">
  <%= render partial: 'web/videos/partials/video_player', locals: {
    video_url: video.file_url,
    thumb_url: video.thumb_url
  }%>
  <div class="section-contents-inner-video-inner-detail">
    <div class="section-contents-inner-video-inner-detail-wrap clearfix">
      <div class="section-contents-inner-video-inner-detail-title">
          <%= render partial: 'web/videos/partials/like', locals: {video: video, videos: @videos, likes: @likes, like: @like, user: current_user} %>
          <a href="/videos/<%= video.id %>" class=""><%= video.title %></a>
      </div>
    </div>
    <div class="section-contents-inner-video-inner-detail-serise clearfix">
      <div class="section-contents-inner-video-inner-detail-serise-inner">
        <div class="section-contents-inner-video-inner-detail-serise-l">
          <div class="section-contents-inner-video-inner-detail-serise-image" style="background-image:url(<%= video.creator.icon_url %>);"></div>
        </div>
        <div class="section-contents-inner-video-inner-detail-serise-r">
          <div class="section-contents-inner-video-inner-detail-serise-text">
            <p><%= video.creator.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="comment">
      <%= link_to 'コメントする', new_video_comment_path(video), class: 'btn btn-default' %>
    </div>
    <div class="video-comments clearfix">
          <ul>
            <% video.comments.each do |comment| %>
              <li>
                <div class="meta">
                  <div class="meta-title">
                    <%= comment.user.nickname %>
                  </div>
                  <div class="user_review">
                    <%= comment.content %>
                  </div>
              </div>
              </li>
            <% end %>
          </ul>
    </div>
  </div>
</div>

app/views/web/videos/partials/_index.html.erb
<div id="section-contents-inner-video">
  <div class="section-contents-inner-video-inner">
    <div class="search-bar">
      <%= render partial: 'web/videos/partials/search_bar', locals: {videos: @videos }%>
    </div>

    <div class="index-title">
      <h1>最新動画</h1>
    </div>
    <ul>
      <% videos.each do |video| %>
        <li>
          <% if video.status_code == "visible" %>
            <%= render partial: 'web/videos/partials/video_player', locals: {
              video_url: video.file_url,
              thumb_url: video.thumb_url
            }%>
            <div class="section-contents-inner-video-inner-detail">
              <div class="section-contents-inner-video-inner-detail-wrap clearfix">
                <div class="section-contents-inner-video-inner-detail-title">
                    <%= render partial: 'web/videos/partials/like', locals: {video: video, videos: @videos, likes: @likes, like: @like, user: current_user} %>
                    <a href="/videos/<%= video.id %>" class=""><%= video.title %></a>
                </div>
              </div>
              <div class="section-contents-inner-video-inner-detail-serise clearfix">
                <div class="section-contents-inner-video-inner-detail-serise-inner">
                  <div class="section-contents-inner-video-inner-detail-serise-l">
                    <div class="section-contents-inner-video-inner-detail-serise-image" style="background-image:url(<%= video.creator.icon_url %>);"></div>
                  </div>
                  <div class="section-contents-inner-video-inner-detail-serise-r">
                    <div class="section-contents-inner-video-inner-detail-serise-text">
                      <p><%= video.creator.name %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/web/videos/partials/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.favorite?(video) %>
    <div class="like-button">
      <%= button_to video_like_path(video, user_id: current_user.id, video_id: video.id), method: :delete, id: "like-button", remote: true do %>
        <%= image_tag("heart-solid.svg") %>
      <% end %>
    </div>
  <% else %>
    <div class="like-button">
      <%= button_to video_likes_path(video, user_id: current_user.id), method: :post, id: "like-button", remote: true do %>
        <%= image_tag("heart-regular.svg") %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/web/videos/partials/_menu_bar.html.erb
<div class="menu">
  <ul class="nav">
    <%= image_tag("align-justify-solid.svg") %>
    <div clsss="menu-bar">
      <% if user_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'マイページ', user_path(current_user) %></li>
      <% else %>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </div>
  </ul>
</div>

app/views/web/videos/partials/_result.html.erb
<div id="section-contents-inner-video">
  <div class="section-contents-inner-video-inner">
    <div class="search-bar">
      <%= render partial: 'web/videos/partials/search_bar', locals: {videos: @videos }%>
    </div>
    <div class="index-title">
      <h1>検索結果</h1>
    </div>
    <ul>
      <% videos.each do |video| %>
        <li>
          <% if video.status_code == "visible" %>
            <%= render partial: 'web/videos/partials/video_player', locals: {
              video_url: video.file_url,
              thumb_url: video.thumb_url
            }%>
            <div class="section-contents-inner-video-inner-detail">
              <div class="section-contents-inner-video-inner-detail-wrap clearfix">
                <div class="section-contents-inner-video-inner-detail-title">
                    <%= render partial: 'web/videos/partials/like', locals: {video: video, videos: @videos, likes: @likes, like: @like, user: current_user} %>
                    <a href="/videos/<%= video.id %>" class=""><%= video.title %></a>
                </div>
              </div>
              <div class="section-contents-inner-video-inner-detail-serise clearfix">
                <div class="section-contents-inner-video-inner-detail-serise-inner">
                  <div class="section-contents-inner-video-inner-detail-serise-l">
                    <div class="section-contents-inner-video-inner-detail-serise-image" style="background-image:url(<%= video.creator.icon_url %>);"></div>
                  </div>
                  <div class="section-contents-inner-video-inner-detail-serise-r">
                    <div class="section-contents-inner-video-inner-detail-serise-text">
                      <p><%= video.creator.name %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/web/videos/partials/_search.html.erb
<div id="section-contents-inner-video">
  <div class="section-contents-inner-video-inner">
    <div class="index-title">
      <h1>検索結果</h1>
    </div>
    <ul>
      <% videos.each do |video| %>
        <li>
          <% if video.status_code == "visible" %>
            <%= render partial: 'web/videos/partials/video_player', locals: {
              video_url: video.file_url,
              thumb_url: video.thumb_url
            }%>
            <div class="section-contents-inner-video-inner-detail">
              <div class="section-contents-inner-video-inner-detail-wrap clearfix">
                <div class="section-contents-inner-video-inner-detail-title">
                  <p>
                    <a href="/videos/<%= video.id %>" class=""><%= video.title %></a>
                    <% if user_signed_in? %>
                      <% if video.favorite?(current_user.id) %>
                        <%= button_to video_like_path(current_user.id, video.id), method: :delete, id: "like-button", remote: true do %>
                          <%= image_tag("icon_red_heart.svg") %>
                          <span>
                            <%= video.likes_count %>
                          </span>
                        <% end %>
                      <% else %>
                        <%= button_to video_likes_path(video), id: "like-button", remote: true do %>
                          <%= image_tag("icon_heart.svg") %>
                          <span>
                            <%= video.likes_count %>
                          </span>
                        <% end %>
                      <% end %>
                    <% else %>
                      <%= image_tag("icon_heart.svg") %>
                        <span>
                          <%= video.likes_count %>
                        </span>
                    <% end %>
                  </p>
                </div>
              </div>
              <div class="section-contents-inner-video-inner-detail-serise clearfix">
                <div class="section-contents-inner-video-inner-detail-serise-inner">
                  <div class="section-contents-inner-video-inner-detail-serise-l">
                    <div class="section-contents-inner-video-inner-detail-serise-image" style="background-image:url(<%= video.creator.icon_url %>);"></div>
                  </div>
                  <div class="section-contents-inner-video-inner-detail-serise-r">
                    <div class="section-contents-inner-video-inner-detail-serise-text">
                      <p><%= video.creator.name %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/web/videos/partials/_search_bar.html.erb
<%= search_form_for(@q, url: search_path, class: 'well') do |f| %>
    <%= f.text_field :title_cont, class: 'form-control', placeholder: "動画を検索" %>
  <%= f.submit '検索', class: 'btn btn-default' %>
<% end %>

app/views/web/videos/partials/_video_player.html.erb
<div class="section-contents-inner-video-inner-player">
  <div class="section-contents-inner-video-inner-bg">
    <div class="section-contents-inner-video-inner-image" style="background-image:url(<%= thumb_url %>);"></div>
  </div>
  <div class="section-contents-inner-media-wrapper">
    <div id="section-contents-inner-media-play" style="background-image:url(<%= thumb_url %>);"></div>
    <video id="section-contents-inner-media-player" width="520" height="924" style="max-width:100%" preload="auto" controls>
      <source src="<%= video_url %>" type="video/mp4" />
    </video>
  </div>
</div>

app/views/web/videos/search.html.erb
<div id="section-contents-inner-video">
  <%= render partial: 'web/videos/partials/result', locals: { videos: @videos} %>
</div>

app/views/web/videos/show.html.erb
<div id="section-contents-inner-video">
  <%= render partial: 'web/videos/partials/contents_section', locals: { video: @video, comments: @comments } %>
</div><!-- /#section-contents-inner-video -->